version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/ #for development
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:123456789@postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - nestjs_network

  postgres:
    image: postgres:14-alpine
    container_name: nestjs_postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - nestjs_network

  redis:
    image: redis/redis-stack-server:latest
    container_name: nestjs_redis
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge
